Esm
MO-Movia/licit-plugin-contrib-multimedia pull request #26
Opened 2023-09-21 11:21 UTC by Jayakrishnan-MS

ESM conversion

2023-12-26 13:20 UTC, Tezra requested changes

2023-12-26 13:20 UTC, Tezra commented on package.json
>    "dependencies": {
these should be peerDependnecies.

2024-01-31 14:18 UTC, rodgersgb approved these changes

2024-01-31 14:30 UTC, Tezra approved these changes

2024-01-31 14:30 UTC, merged